version: "3.7"
services: 
    db: 
        image: postgres:12.1-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./database/pgsql:/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
    web:
        build: .
        ports: 
            - "3000:3000"
        volumes: 
            - ./backend:/var/www/interaktiv
        depends_on:
            - db

# docker-compose up
# docker-compose stop
# docker-compose start
# docker-compose images
