#!groovy

properties([disableConcurrentBuilds()])

pipeline {
    agent {
        label 'master'
    }

    triggers { pollSCM('* * * * *') }

    options {
        buildDiscarder(
            logRotator(
                numToKeepStr: '10',
                artifactNumToKeepStr: '10'
            )
        )
        timestamps()
    }

    stages {
        stage("Build backend") {
            steps {
                sh './sripts/backend_build.sh'
                // script {
                //     try {
                //         sh "git diff --quiet --exit-code HEAD~1..HEAD backend/"
                //     } catch (err) {
                //         sh 'chmod +x jenkins/scripts/backend_build.sh'
                //     }
                // }
            }
        }

    //     stage("Build frontend") {
    //         steps {
    //             script {
    //                 try {
    //                     sh "git diff --quiet --exit-code HEAD~1..HEAD frontend/"
    //                 } catch (err) {
    //                     sh 'chmod +x jenkins/scripts/frontend_build.sh'
    //                 }
    //             }
    //         }
    //     }
    // }
}
