#!groovy

properties([disableConcurrentBuilds()])

pipeline {
    agent {
        label 'master'
    }

    triggers { pollSCM('* * * * *') }

    options {
        buildDiscarder(
            logRotator(
                numToKeepStr: '10',
                artifactNumToKeepStr: '10'
            )
        )
        timestamps()
    }

    stages {
        stage("Build backend") {
            steps {
                try {
                    sh "git diff --quiet --exit-code HEAD~1..HEAD backend/"
                } catch (err) {
                    sh 'chmod +x jenkins/scripts/backend_build.sh'
                }
            }


            // if (checkFolderForDiffs('backend/')) {
            //     steps {
            //         sh 'chmod +x jenkins/scripts/backend_build.sh'
            //         // sh './jenkins/scripts/backend_build.sh'
            //     }
            // }
        }
    }
}
